### PR TITLE
Bump to Kubernetes 1.9.2

### PR DESCRIPTION
**Pull request by liztio**

### CODE REVIEW

**Comment by avattathil** [comment]
@liztio please send PR to the develop branch

**Comment by liztio** [comment]
ah, my bad!

**Comment by avattathil** [comment]
No worries

**Comment by timothysc** [comment]
@avattathil when will master get updated and the cloud formation template go-live?  

/cc @chuckha

**Comment by avattathil** [comment]
Change are in master now. template are live

**Pull request merged**
