### PR TITLE
Kubernetes 1.6.4

### PR DESCRIPTION
**Pull request by kensimon**

### CODE REVIEW

**Comment by kensimon** [comment]
@anthonynv FYI

**Comment by avattathil** [comment]
@kensimon Can you edit the PR to point to our develop branch. (aws-quickstart/quickstart-heptio:develop) 

Also, Do you have a go-live date? or is it ready to go-live now?

**Comment by kensimon** [comment]
Oops, sorry about that.

Yeah we're ready to go live now, there aren't any documentation updates to coordinate with so whenever you're ready.

**Comment by avattathil** [comment]
@kensimon  
https://github.com/aws-quickstart/quickstart-heptio/releases/tag/May

**Pull request merged**
